- hosts: slwwwbase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
  
    - name: Get mod_proxy_uwsgi.c
      get_url:
        url: ftp://192.1.1.181/couchdb/mod_proxy_uwsgi.c
        dest: /home/smartlis
        mode: 0777
        
    - name: Install extension module "mod_proxy_uwsgi"
      become: yes
      shell: apxs2 -i -c /home/smartlis/mod_proxy_uwsgi.c
      
    - name: Create "proxy_uwsgi.load" file
      copy:
        content: ""
        dest: /etc/apache2/mods-available/proxy_uwsgi.load
      
    - name: Configure "proxy_uwsgi.load" file
      blockinfile:
        path: /etc/apache2/mods-available/proxy_uwsgi.load
        block: |
          #Depends: proxy
          LoadModule proxy_uwsgi_module /usr/lib/apache2/modules/mod_proxy_uwsgi.so
    
    - name: Delete file /etc/apache2/mods-available/info.conf
      file:
        path: /etc/apache2/mods-available/info.conf
        state: absent
        
    - name: Create empty file /etc/apache2/mods-available/info.conf
      file:
        path: /etc/apache2/mods-available/info.conf
        state: touch
        
    - name: Configure /etc/apache2/mods-available/info.conf file
      blockinfile:
        path: /etc/apache2/mods-available/info.conf
        block: |
          <IfModule mod_info.c>

                # Allow remote server configuration reports, with the URL of
                #  http://servername/server-info (requires that mod_info.c be loaded).
                # Uncomment and change the "192.0.2.0/24" to allow access from other hosts.
                #
                <Location /server-info>
                    SetHandler server-info
                    #Require local
                    Require ip "{{ lab_subnet }}"
                </Location>

          </IfModule>

          # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
    
    - name: Delete file /etc/apache2/mods-available/status.conf
      file:
        path: /etc/apache2/mods-available/status.conf
        state: absent
        
    - name: Create empty file /etc/apache2/mods-available/status.conf
      file:
        path: /etc/apache2/mods-available/status.conf
        state: touch
        
    - name: Configure /etc/apache2/mods-available/status.conf file
      blockinfile:
        path: /etc/apache2/mods-available/status.conf
        block: |
          
          <IfModule mod_status.c>
                # Allow server status reports generated by mod_status,
                # with the URL of http://servername/server-status
                # Uncomment and change the "192.0.2.0/24" to allow access from other hosts.

                <Location /server-status>
                        SetHandler server-status
                        #Require local
                        Require ip "{{ lab_subnet }}"
                </Location>

                # Keep track of extended status information for each request
                ExtendedStatus On

                # Determine if mod_status displays the first 63 characters of a request or
                # the last 63, assuming the request itself is greater than 63 chars.
                # Default: Off
                #SeeRequestTail On


                <IfModule mod_proxy.c>
                        # Show Proxy LoadBalancer status in mod_status
                        ProxyStatus On
                </IfModule>


          </IfModule>

          # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
          
    - name: Delete file /etc/apache2/mods-available/proxy_balancer.conf
      file:
        path: /etc/apache2/mods-available/proxy_balancer.conf
        state: absent
        
    - name: Create empty file /etc/apache2/mods-available/proxy_balancer.conf
      file:
        path: /etc/apache2/mods-available/proxy_balancer.conf
        state: touch
      
    - name: Configure /etc/apache2/mods-available/proxy_balancer.conf file
      blockinfile:
        path: /etc/apache2/mods-available/proxy_balancer.conf
        block: |
        
            <IfModule mod_proxy_balancer.c>

                # Balancer manager enables dynamic update of balancer members
                # (needs mod_status). Uncomment to enable.
                #
                <IfModule mod_status.c>
                  <Location /balancer-manager>
                          SetHandler balancer-manager
                          Require ip "{{ lab_subnet }}"
                  </Location>
                </IfModule>

            </IfModule>

            # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
            
    - name: Enable apache2 modules
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - info
        - lbmethod_byrequests
        - proxy
        - proxy_balancer
        - proxy_connect
        - proxy_express
        - proxy_fcgi
        - proxy_fdpass
        - proxy_html
        - proxy_http
        - proxy_scgi
        - slotmem_plain
        - ssl
        - proxy_uwsgi
        - proxy_wstunnel
        - xml2enc
       
    - name: restart apache2 service
      service:
        name: apache2
        state: restarted
        
    - name: Create fqdn.conf file
      file:
        path: /etc/apache2/conf-available/fqdn.conf
        state: touch
        
    - name: Configure fqdn.conf file
      lineinfile:
        path: /etc/apache2/conf-available/fqdn.conf
        line: 'ServerName 192.1.1.220'
        
    - name: Final apache2 configuration
      become: yes
      shell: a2enconf fqdn && a2dissite 000-default
       
    - name: reload apache2
      service:
        name: apache2
        state: reloaded
