- hosts: slwwwbase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
  
    - name: install apache2
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - apache2-dev
        
    - name: start apache2
      service:
        name: apache2
        state: started
